### ISSUE TITLE
Portfoly link when logged in

### ISSUE THREAD

**Issue by choppen5** [tomarrell/Portfoly-IssueTracker#7]
1. Logged into porfoly, I want to go back to my home project screen - https://portfoly.io/user/choppen5
2. I press the portfoly link on the upper left corner, I am navigated to https://portfoly.io, and need to log in again. Particularly painful on mobile.

what should happen: I am sent to https://portfoly.io/user/choppen5 if I am logged in.

**Comment by tomarrell** [comment]
In the top right the avatar is a link back to the user's profile. This may be a little subtle however and we should discuss doing the same for the Portfoly logo. I tend to agree that they should both link back to the profile.

**Comment by tomarrell** [comment]
Made the logo route to the user's profile when logged in and to the landing page if logged out.
